name: CI Build validation & test

on:
  pull_request:
    branches:
      - main

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 dependency installation
        uses: ./.github/actions/pnpm-install

      # Run the linter and verifies the formatting of a set of files. If any errors are found the process exits with a code of 1.
      - name: Validate code standards
        run: pnpm validate:ci
      
      # Runs the build script for each workspace
      - name: Build
        run: pnpm build